---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  coffeelint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - "**.erb"
  - "**.haml"
  - "**.rb"
exclude_paths:
- app/assets
- bin/
- config/
- db/
- spec/
- vendor/
