# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3914dfe051d9a79ba6a189b28d1b4fc1da005c16be2888c2181a1e4af4689c5e15a4300fb73c9bc16f3eb79c1eea2605f571bd2f903cccfbf181692c7b7ed18f

test:
  secret_key_base: 867fd8ab3563661ae8ddba3b6e26948254f791433a21ab4cdb7e603ee628523d88a5ff5270f03d64294d0189992d13dfed174a4a3103df9330e742e68b732ecf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
